config/routes.rb
Sakana::Application.routes.draw do

  resources :pickups

  resources :infos

  devise_for :admins

  resources :divelogs

  resources :divesites

  resources :tags

  resources :areas

  resources :genres

  resources :details

  resources :pictures 

  root :to => "top#index"
  resource :top ,:controller => 'top' do
    match ':action' ,:controller => :top
  end

  devise_for :admins
  get 'admins', :to => 'top#index', :as => :admin_root

    

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :timeoutable, :lockable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/area.rb
class Area < ActiveRecord::Base
  has_many :divesites
end

app/models/detail.rb
class Detail < ActiveRecord::Base
  has_and_belongs_to_many :pictures
  belongs_to :genre


end

app/models/details_pictures.rb
class DetailsPictures < ActiveRecord::Base
end

app/models/divelog.rb
class Divelog < ActiveRecord::Base
  belongs_to :divesite
  has_many :pictures
end

app/models/divesite.rb
class Divesite < ActiveRecord::Base
  belongs_to :area
  has_many :divelogs
#  has_many :pictures, :through => :divelogs
  has_many :pictures
  has_attached_file :sitemap, :styles => { :medium=> "720x540>", :thumb => "105x80>" }

end

app/models/exif.rb
class Exif < ActiveRecord::Base
    belongs_to :picture
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :details
end

app/models/info.rb
class Info < ActiveRecord::Base
end

app/models/pickup.rb
class Pickup < ActiveRecord::Base
end

app/models/picture.rb
require 'exifr'
class Picture < ActiveRecord::Base
  has_and_belongs_to_many :details
  has_and_belongs_to_many :tags
  belongs_to :divelog
  belongs_to :divesite
  has_one :exif

  has_attached_file :image, :styles => { :medium => "720x540>", :thumb => "105x80>" }

  after_save :process_exif

    def process_exif
      cnt = Exif.where(:picture_id => self.id).count
      if cnt == 0 
      file = self.image.path
        exif = EXIFR::JPEG.new file
        pic_exif = self.build_exif
            pic_exif.camera_brand = exif.make
            pic_exif.camera_model = exif.model
            pic_exif.shot_date_time = exif.date_time
        pic_exif.save
      end
    end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :pictures
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  # GET /genres
  # GET /genres.xml
  def index
    @genres = Genre.paginate(:page => params[:page], :per_page => 20, :order => 'genrename asc')

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @genres }
    end
  end

  # GET /genres/1
  # GET /genres/1.xml
  def show
    @genre = Genre.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @genre }
    end
  end

  # GET /genres/new
  # GET /genres/new.xml
  def new
    @genre = Genre.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @genre }
    end
  end

  # GET /genres/1/edit
  def edit
    @genre = Genre.find(params[:id])
  end

  # POST /genres
  # POST /genres.xml
  def create
    @genre = Genre.new(params[:genre])

    respond_to do |format|
      if @genre.save
        format.html { redirect_to(@genre, :notice => 'Genre was successfully created.') }
        format.xml  { render :xml => @genre, :status => :created, :location => @genre }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @genre.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /genres/1
  # PUT /genres/1.xml
  def update
    @genre = Genre.find(params[:id])

    respond_to do |format|
      if @genre.update_attributes(params[:genre])
        format.html { redirect_to(@genre, :notice => 'Genre was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @genre.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.xml
  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy

    respond_to do |format|
      format.html { redirect_to(genres_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @pictures = Picture.order('RAND()').limit(6)
    @infos = Info.order('created_at desc').limit(3)
  end

end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/divesites_helper.rb
module DivesitesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/pickups_helper.rb
module PickupsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/genres/_form.html.erb
<div id="index-right">
</div>

<div id="main">
<%= form_for(@genre) do |f| %>
  <% if @genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% @genre.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :genrename %><br />
    <%= f.text_field :genrename %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/genres/edit.html.erb
<div id="index-right">
</div>

<div id="main">
<%= render 'form' %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>
</div>

app/views/genres/index.html.erb
<% content_for :title do %>
種類一覧
<% end %>

<div id="index-right" class="clearfix">
</div>

<div id="main">
<div id="main_cont">
<table id="detail">
  <tr>
    <th>種別</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @genres.each do |genre| %>
  <tr>
    <td><%= genre.genrename %></td>
    <td><%= link_to '見る', details_path(:genre_id => genre.id) %></td>
     <% if admin_signed_in? %>
    <td><%= link_to 'Edit', edit_genre_path(genre) %></td>
    <td><%= link_to 'Destroy', genre, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
<% end %>
</table>

<br />

<% if admin_signed_in? %>
<%= link_to 'New Genre', new_genre_path %>
<% end %>
</div>

<%= will_paginate @genres %>

</div>

app/views/genres/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', genres_path %>

app/views/genres/show.html.erb
<div id="index-right">
</div>

<div id="main">
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @genre.genrename %>
</p>


<%= link_to 'Edit', edit_genre_path(@genre) %> |
<%= link_to 'Back', genres_path %>

</div>