config/routes.rb
Sakana::Application.routes.draw do

  resources :pickups

  resources :infos

  devise_for :admins

  resources :divelogs

  resources :divesites

  resources :tags

  resources :areas

  resources :genres

  resources :details

  resources :pictures 

  root :to => "top#index"
  resource :top ,:controller => 'top' do
    match ':action' ,:controller => :top
  end

  devise_for :admins
  get 'admins', :to => 'top#index', :as => :admin_root

    

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :timeoutable, :lockable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/area.rb
class Area < ActiveRecord::Base
  has_many :divesites
end

app/models/detail.rb
class Detail < ActiveRecord::Base
  has_and_belongs_to_many :pictures
  belongs_to :genre


end

app/models/details_pictures.rb
class DetailsPictures < ActiveRecord::Base
end

app/models/divelog.rb
class Divelog < ActiveRecord::Base
  belongs_to :divesite
  has_many :pictures
end

app/models/divesite.rb
class Divesite < ActiveRecord::Base
  belongs_to :area
  has_many :divelogs
#  has_many :pictures, :through => :divelogs
  has_many :pictures
  has_attached_file :sitemap, :styles => { :medium=> "720x540>", :thumb => "105x80>" }

end

app/models/exif.rb
class Exif < ActiveRecord::Base
    belongs_to :picture
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :details
end

app/models/info.rb
class Info < ActiveRecord::Base
end

app/models/pickup.rb
class Pickup < ActiveRecord::Base
end

app/models/picture.rb
require 'exifr'
class Picture < ActiveRecord::Base
  has_and_belongs_to_many :details
  has_and_belongs_to_many :tags
  belongs_to :divelog
  belongs_to :divesite
  has_one :exif

  has_attached_file :image, :styles => { :medium => "720x540>", :thumb => "105x80>" }

  after_save :process_exif

    def process_exif
      cnt = Exif.where(:picture_id => self.id).count
      if cnt == 0 
      file = self.image.path
        exif = EXIFR::JPEG.new file
        pic_exif = self.build_exif
            pic_exif.camera_brand = exif.make
            pic_exif.camera_model = exif.model
            pic_exif.shot_date_time = exif.date_time
        pic_exif.save
      end
    end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :pictures
end

app/controllers/pickups_controller.rb
class PickupsController < ApplicationController
  # GET /pickups
  # GET /pickups.xml
  def index
    @pickups = Pickup.order('created_at DESC')
    @pickups = @pickups.paginate(:page => params[:page], :per_page => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pickups }
    end
  end

  # GET /pickups/1
  # GET /pickups/1.xml
  def show
    @pickups = Pickup.order('created_at DESC')
    @pickups = @pickups.paginate(:page => params[:page], :per_page => 20)
    @pickup = Pickup.find(params[:id])
    @picture_first = Picture.find(@pickup.picture.to_i)
    @detail = @picture_first.details.last
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pickup }
    end
  end

  # GET /pickups/new
  # GET /pickups/new.xml
  def new
    @pickup = Pickup.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pickup }
    end
  end

  # GET /pickups/1/edit
  def edit
    @pickup = Pickup.find(params[:id])
  end

  # POST /pickups
  # POST /pickups.xml
  def create
    @pickup = Pickup.new(params[:pickup])

    respond_to do |format|
      if @pickup.save
        format.html { redirect_to(@pickup, :notice => 'Pickup was successfully created.') }
        format.xml  { render :xml => @pickup, :status => :created, :location => @pickup }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @pickup.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pickups/1
  # PUT /pickups/1.xml
  def update
    @pickup = Pickup.find(params[:id])

    respond_to do |format|
      if @pickup.update_attributes(params[:pickup])
        format.html { redirect_to(@pickup, :notice => 'Pickup was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pickup.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pickups/1
  # DELETE /pickups/1.xml
  def destroy
    @pickup = Pickup.find(params[:id])
    @pickup.destroy

    respond_to do |format|
      format.html { redirect_to(pickups_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @pictures = Picture.order('RAND()').limit(6)
    @infos = Info.order('created_at desc').limit(3)
  end

end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/divesites_helper.rb
module DivesitesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/pickups_helper.rb
module PickupsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/pickups/_form.html.erb
<div id="index-right">
</div>

<div id="main">
<%= form_for(@pickup) do |f| %>
  <% if @pickup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pickup.errors.count, "error") %> prohibited this pickup from being saved:</h2>

      <ul>
      <% @pickup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= f.label :picture %><br />
  <%= f.number_field :picture %><br />
  <%= f.label :comment %><br />
  <%= f.text_area :comment %><br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pickups/edit.html.erb
<h1>Editing pickup</h1>

<%= render 'form' %>

<%= link_to 'Show', @pickup %> |
<%= link_to 'Back', pickups_path %>

app/views/pickups/index.html.erb
<% content_for :title do %>
オススメ写真一覧
<% end %>

<div id="index-right">
</div>

<div id="main">
<table>
  <tr>
    <th>更新日</th>
    <th>コメント</th>
    <th></th>
    <th></th>
  </tr>

<% @pickups.each do |pickup| %>
  <tr>
    <td><%= link_to pickup.updated_at, pickup %></td>
    <td><%= truncate(pickup.comment, :length => 15) %></td>
    <% if admin_signed_in? %>
    <td><%= link_to 'Edit', edit_pickup_path(pickup) %></td>
    <td><%= link_to 'Destroy', pickup, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>
<p>
<%= will_paginate @pickups %>
</p>
<br />

<% if admin_signed_in? %>
<%= link_to 'New Pickup', new_pickup_path %>
<% end %>

</div>

app/views/pickups/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', pickups_path %>

app/views/pickups/show.html.erb
<%= render 'layouts/shared/javascript' %>

<% content_for :title do %>
<%= @pickup.created_at.strftime("%Y-%m-%d") %> &nbsp;オススメ写真(<%= @detail.name %>)
<% end %>

<div id="index-right">
 <div id="whatsnew">
   <p>更新日</p>
 </div>
 <div id="whatsnew_cont">
   <% @pickups.each do |pickup| %>
   <dl>
     <dt><%= link_to pickup.created_at.strftime("%Y-%m-%d"), pickup %></dt>
     <dd><%= truncate(pickup.comment, :length => 15) %></dd>
   <% end %>
 </div>
 <%= will_paginate @pickups %>
</div>

<div id="main">
<p id="notice"><%= notice %></p>
 <h2>
     更新日：<%= @pickup.created_at.strftime("%Y-%m-%d") %> &nbsp; <%= @detail.name %>
 </h2>
 <%= image_tag(@picture_first.image.url(:medium)) %>
 <div id="main_cont">
 <p><%= @pickup.comment %></p>
 <p><%= link_to @detail.name, detail_path(@detail, :picture_id => @picture_first.id) %>を見る</p>
<table><tr><td><a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal" data-via="akiko74" data-lang="ja">ツイート</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script></td>
<td><div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#appId=142642749161266&amp;xfbml=1"></script><fb:like href="" send="true" layout="button_count" width="100" show_faces="false" font="tahoma"></fb:like></td>
<td><g:plusone size="medium"></g:plusone></td>
</tr>
</table>

<% if admin_signed_in? %>
<p><%= link_to 'Edit', edit_pickup_path(@pickup) %></p>
<p><%= link_to 'Destroy', @pickup, :confirm => 'Are you sure?', :method => :delete %></p>
<% end %>
<script type="text/javascript" src="https://apis.google.com/js/plusone.js">
  {lang: 'ja'}
</script>
</div>