config/routes.rb
Sakana::Application.routes.draw do

  resources :pickups

  resources :infos

  devise_for :admins

  resources :divelogs

  resources :divesites

  resources :tags

  resources :areas

  resources :genres

  resources :details

  resources :pictures 

  root :to => "top#index"
  resource :top ,:controller => 'top' do
    match ':action' ,:controller => :top
  end

  devise_for :admins
  get 'admins', :to => 'top#index', :as => :admin_root

    

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :timeoutable, :lockable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/area.rb
class Area < ActiveRecord::Base
  has_many :divesites
end

app/models/detail.rb
class Detail < ActiveRecord::Base
  has_and_belongs_to_many :pictures
  belongs_to :genre


end

app/models/details_pictures.rb
class DetailsPictures < ActiveRecord::Base
end

app/models/divelog.rb
class Divelog < ActiveRecord::Base
  belongs_to :divesite
  has_many :pictures
end

app/models/divesite.rb
class Divesite < ActiveRecord::Base
  belongs_to :area
  has_many :divelogs
#  has_many :pictures, :through => :divelogs
  has_many :pictures
  has_attached_file :sitemap, :styles => { :medium=> "720x540>", :thumb => "105x80>" }

end

app/models/exif.rb
class Exif < ActiveRecord::Base
    belongs_to :picture
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :details
end

app/models/info.rb
class Info < ActiveRecord::Base
end

app/models/pickup.rb
class Pickup < ActiveRecord::Base
end

app/models/picture.rb
require 'exifr'
class Picture < ActiveRecord::Base
  has_and_belongs_to_many :details
  has_and_belongs_to_many :tags
  belongs_to :divelog
  belongs_to :divesite
  has_one :exif

  has_attached_file :image, :styles => { :medium => "720x540>", :thumb => "105x80>" }

  after_save :process_exif

    def process_exif
      cnt = Exif.where(:picture_id => self.id).count
      if cnt == 0 
      file = self.image.path
        exif = EXIFR::JPEG.new file
        pic_exif = self.build_exif
            pic_exif.camera_brand = exif.make
            pic_exif.camera_model = exif.model
            pic_exif.shot_date_time = exif.date_time
        pic_exif.save
      end
    end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :pictures
end

app/controllers/divesites_controller.rb
class DivesitesController < ApplicationController
  # GET /divesites
  # GET /divesites.xml
  def index
    @divesites = Divesite.order('area_id asc', 'pointname asc').paginate(:page => params[:page], :per_page => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @divesites }
    end
  end

  # GET /divesites/1
  # GET /divesites/1.xml
  def show
    @divesite = Divesite.find(params[:id])
    @pictures = @divesite.pictures.joins(:details).order('id desc')
    @details = Detail.joins(:pictures).where('pictures.id' => @pictures.map{|p| p.id}).uniq
    @pictures = @pictures.paginate(:page => params[:page], :per_page => 10)
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @divesite }
    end
  end

  # GET /divesites/new
  # GET /divesites/new.xml
  def new
    @divesite = Divesite.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @divesite }
    end
  end

  # GET /divesites/1/edit
  def edit
    @divesite = Divesite.find(params[:id])
  end

  # POST /divesites
  # POST /divesites.xml
  def create
    @divesite = Divesite.new(params[:divesite])

    respond_to do |format|
      if @divesite.save
        format.html { redirect_to(@divesite, :notice => 'Divesite was successfully created.') }
        format.xml  { render :xml => @divesite, :status => :created, :location => @divesite }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @divesite.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /divesites/1
  # PUT /divesites/1.xml
  def update
    @divesite = Divesite.find(params[:id])

    respond_to do |format|
      if @divesite.update_attributes(params[:divesite])
        format.html { redirect_to(@divesite, :notice => 'Divesite was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @divesite.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /divesites/1
  # DELETE /divesites/1.xml
  def destroy
    @divesite = Divesite.find(params[:id])
    @divesite.destroy

    respond_to do |format|
      format.html { redirect_to(divesites_url) }
      format.xml  { head :ok }
    end
  end

  def generate_area_list
    @areas = Area.find.all
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @pictures = Picture.order('RAND()').limit(6)
    @infos = Info.order('created_at desc').limit(3)
  end

end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/divesites_helper.rb
module DivesitesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/pickups_helper.rb
module PickupsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/divesites/_form.html.erb
<div id="index-right">
</div>

<div id="main">
<%= form_for(@divesite, :html => { :multipart => true }) do |f| %>
  <% if @divesite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@divesite.errors.count, "error") %> prohibited this divesite from being saved:</h2>

      <ul>
      <% @divesite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :pointname %><br />
    <%= f.text_field :pointname %>
    <%= collection_select(:divesite, :area_id, Area.all, :id, :areaname) %>
    <%= f.file_field :sitemap %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/divesites/edit.html.erb
<h1>Editing divesite</h1>

<%= render 'form' %>

<%= link_to 'Show', @divesite %> |
<%= link_to 'Back', divesites_path %>

app/views/divesites/index.html.erb
<% content_for :title do %>
ダイブサイト一覧
<% end %>

<div id="index-right" class="clearfix">
</div>

<div id="main">
  <div id="main_cont">
    <table>
      <tr>
        <th>エリア名</th>
        <th>ポイント名</th>
      </tr>

<% @divesites.each do |divesite| %>
  <tr>
    <td><%= divesite.area.areaname %></td>
    <td><%= link_to divesite.pointname, divesite %></td>
    <% if admin_signed_in? %>    
    <td><%= link_to 'Edit', edit_divesite_path(divesite) %></td>
    <td><%= link_to 'Destroy', divesite, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
<% end %>
</table>
<%= will_paginate @divesites %>

<br />

<% if admin_signed_in? %>    
<%= link_to 'New Divesite', new_divesite_path %>
<% end %>

  </div>
</div>

app/views/divesites/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', divesites_path %>

app/views/divesites/show.html.erb
<% content_for :title do @divesite.pointname %>
<% end %>

<%= notice %>
<%= render 'layouts/shared/rightthumb' %>

<div id="main">
  <h3>ポイント名: <%= @divesite.pointname %></h3>

<%= image_tag @divesite.sitemap.url(:original) %>
  <table>
    <tr>
      <th>このポイントで見られた魚</th>
    </tr>
    <tr>
      <td>
         <% @details.each do |detail| %>
         <%= link_to detail.name, detail_path(:id => detail.id, :divesite_id => @divesite.id) %>
         <% end %>
      </td>
    </tr>
  </table>
</div>