config/routes.rb
Sakana::Application.routes.draw do

  resources :pickups

  resources :infos

  devise_for :admins

  resources :divelogs

  resources :divesites

  resources :tags

  resources :areas

  resources :genres

  resources :details

  resources :pictures 

  root :to => "top#index"
  resource :top ,:controller => 'top' do
    match ':action' ,:controller => :top
  end

  devise_for :admins
  get 'admins', :to => 'top#index', :as => :admin_root

    

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :timeoutable, :lockable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/area.rb
class Area < ActiveRecord::Base
  has_many :divesites
end

app/models/detail.rb
class Detail < ActiveRecord::Base
  has_and_belongs_to_many :pictures
  belongs_to :genre


end

app/models/details_pictures.rb
class DetailsPictures < ActiveRecord::Base
end

app/models/divelog.rb
class Divelog < ActiveRecord::Base
  belongs_to :divesite
  has_many :pictures
end

app/models/divesite.rb
class Divesite < ActiveRecord::Base
  belongs_to :area
  has_many :divelogs
#  has_many :pictures, :through => :divelogs
  has_many :pictures
  has_attached_file :sitemap, :styles => { :medium=> "720x540>", :thumb => "105x80>" }

end

app/models/exif.rb
class Exif < ActiveRecord::Base
    belongs_to :picture
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :details
end

app/models/info.rb
class Info < ActiveRecord::Base
end

app/models/pickup.rb
class Pickup < ActiveRecord::Base
end

app/models/picture.rb
require 'exifr'
class Picture < ActiveRecord::Base
  has_and_belongs_to_many :details
  has_and_belongs_to_many :tags
  belongs_to :divelog
  belongs_to :divesite
  has_one :exif

  has_attached_file :image, :styles => { :medium => "720x540>", :thumb => "105x80>" }

  after_save :process_exif

    def process_exif
      cnt = Exif.where(:picture_id => self.id).count
      if cnt == 0 
      file = self.image.path
        exif = EXIFR::JPEG.new file
        pic_exif = self.build_exif
            pic_exif.camera_brand = exif.make
            pic_exif.camera_model = exif.model
            pic_exif.shot_date_time = exif.date_time
        pic_exif.save
      end
    end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :pictures
end

app/controllers/divelogs_controller.rb
class DivelogsController < ApplicationController
  # GET /divelogs
  # GET /divelogs.xml
  def index
    @divelogs = Divelog.order('start_date desc').paginate(:page => params[:page], :per_page => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @divelogs }
    end
  end

  # GET /divelogs/1
  # GET /divelogs/1.xml
  def show
    @divelog = Divelog.find(params[:id])
    @pictures = Picture.where(:divelog_id => params[:id])
    @pictures = @pictures.paginate(:page => params[:page], :per_page => 10)
    @details = Detail.joins(:pictures).where('pictures.id' =>@pictures.map{|p| p.id}).uniq
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @divelog }
    end
  end

  # GET /divelogs/new
  # GET /divelogs/new.xml
  def new
    @divelog = Divelog.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @divelog }
    end
  end

  # GET /divelogs/1/edit
  def edit
    @divelog = Divelog.find(params[:id])
  end

  # POST /divelogs
  # POST /divelogs.xml
  def create
    @divelog = Divelog.new(params[:divelog])

    respond_to do |format|
      if @divelog.save
        format.html { redirect_to(@divelog, :notice => 'Log was successfully created.') }
        format.xml  { render :xml => @divelog, :status => :created, :location => @divelog }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @divelog.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /divelogs/1
  # PUT /divelogs/1.xml
  def update
    @divelog = Divelog.find(params[:id])

    respond_to do |format|
      if @divelog.update_attributes(params[:divelog])
        format.html { redirect_to(@divelog, :notice => 'Log was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @divelog.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /divelogs/1
  # DELETE /divelogs/1.xml
  def destroy
    @divelog = Divelog.find(params[:id])
    @divelog.destroy

    respond_to do |format|
      format.html { redirect_to(divelogs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/divesites_helper.rb
module DivesitesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/pickups_helper.rb
module PickupsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/divelogs/_form.html.erb
<div id="index-right">
</div>

<div id="main">
<%= form_for(@divelog) do |f| %>
  <% if @divelog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@divelog.errors.count, "error") %> prohibited this divelog from being saved:</h2>

      <ul>
      <% @divelog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :startdate %>
    <%= f.datetime_select(:start_date, :start_year => 2004) %><br />
    <%= f.label :enddate %>
    <%= f.datetime_select :end_date %><br />
    <%= collection_select(:divelog, :divesite_id, Divesite.all, :id, :pointname) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/divelogs/edit.html.erb
<h1>Editing Divelog</h1>

<%= render 'form' %>

<%= link_to 'Show', @divelog %> |
<%= link_to 'Back', divelogs_path %>

app/views/divelogs/index.html.erb
<% content_for :title do %>
ダイブログ一覧
<% end %>

<div id="index-right">
</div>

<div id="main">
<h2>ダイブログ</h2>

<table>
  <tr>
  <th>日付</th>
  <th>ポイント</th>
  <tr>
  <% @divelogs.each do |divelog| %>
    <tr>
      <td><%= link_to divelog.start_date.strftime("%Y-%m-%d %H:%M"), divelog %></td>
      <td><%= link_to divelog.divesite.pointname, divesite_path(:id=> divelog.divesite.id) %>
        <% if admin_signed_in? %>
          <td><%= link_to 'Edit', edit_divelog_path(divelog) %></td>
          <td><%= link_to 'Destroy', divelog, :confirm => 'Are you sure?', :method => :delete %></td>
        <% end %>
    </tr>
  <% end %>
</table>
<p>
<%= will_paginate @divelogs %>
</p>
<br />

<% if admin_signed_in? %>
<%= link_to 'New Divelog', new_divelog_path %>
<% end %>

</div>

app/views/divelogs/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', divelogs_path %>

app/views/divelogs/show.html.erb
<% content_for :title do @divelog.start_date %>
<% end %>

<%= render 'layouts/shared/rightthumb' %>
<div id="main">

<p id="notice"><%= notice %></p>

<table>
<tr>
  <th>ダイビングの日付:</th>
</tr>
<tr>
  <td><%= @divelog.start_date %></td>
</tr>
<tr>
  <th>ポイント:</th>
</tr>
<tr>
  <td><%= @divelog.divesite.pointname %>／<%= @divelog.divesite.area.areaname %></td>
</tr>
<tr>
   <th>見られた魚</th>
</tr>
<tr><td>
   <% @details.each do |detail| %>
   <% @picture = detail.pictures.first %>
   <%= link_to detail.name, detail_path(:id => detail.id, :picture_id => @picture.id) %><% end %>
   </td>
</tr>
</table>
</div>